### Installation Package 

In [ ]:
%%capture 
%pip install torch

In [4]:
%pip install torchaudio torchvision

  Using cached torchaudio-2.0.2-cp310-cp310-manylinux1_x86_64.whl (4.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.0/6.0 MB 66.0 MB/s eta 0:00:00:00:0100:01
Note: you may need to restart the kernel to use updated packages.


# Torch Practice 

In [14]:
import torch 
from IPython.display import display as disp

In [20]:
x = torch.tensor([2,4,1],dtype=torch.float32,requires_grad=True)
y = (x**3).sum()
disp(x)
disp(y)


tensor([2., 4., 1.], requires_grad=True)

tensor(73., grad_fn=<SumBackward0>)

In [21]:
y.backward()
dy_dx = x.grad
dy_dx

tensor([12., 48.,  3.])

In [22]:
x.grad.zero_()


tensor([0., 0., 0.])